name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/cache@v2
        id: cache-qt
        with:
          path: ../Qt
          key: ${{ runner.os }}/Qt/5.15.0
      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.0
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - uses: actions/checkout@v2
      - name: msvc build
        shell: cmd
        run: build ci
      - name: generate release note
        id: release_note
        run: echo ("::set-output name=note::" + (python releaselog.py ${{ github.ref }}))
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.release_note.outputs.note }}
          draft: false
          prerelease: false
      - id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./deploy/DBLParse-core/dblp.exe
          asset_name: dblp.exe
          asset_content_type: application/octet-stream