name: Ubuntu
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'scripts/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-Qt5.14.2-Cache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.5.3
        with:
          version: 5.14.2
          target: desktop
          modules: qtwebengine
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - name: Pull codes
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build GCC
        run: |
          g++ -v
          qmake --version
          qmake
          make
