name: Windows
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'scripts/**'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}/Qt/5.14.2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.5.3
        with:
          version: 5.14.2
          target: desktop
          arch: win64_msvc2017_64
          modules: qtwebengine
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Pull codes
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build MSVC
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          qmake --version
          qmake
          nmake