name: Windows
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache 
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.5.3
        with:
          version: 5.12.7
          target: desktop
          arch: win64_msvc2017_64
          modules: qtwebengine
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Pull codes
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build MSVC
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          qmake
          nmake
      - name: Package
        env:
          VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC'
        shell: pwsh
        run: |
          New-Item -ItemType Directory DBLParse
          Copy-Item release\DBLParse.exe DBLParse\
          cd DBLParse
          windeployqt DBLParse.exe > deploy.log
          cd ..
          Copy-Item .\degeneracy_cliques.exe .\DBLParse\
          pip install numpy
          python .\generate_nCr.py
          Copy-Item .\nCr.txt .\DBLParse\
          Compress-Archive -Path .\DBLParse\ DBLParse.zip
      - name: Upload release
        uses: actions/upload-artifact@v1
        with: 
          name: Package
          path: DBLParse.zip
      - name: Upload log
        uses: actions/upload-artifact@v1
        with: 
          name: Package
          path: deploy.log
      