name: Windows
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'scripts/**'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache 
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.5.3
        with:
          version: 5.12.7
          target: desktop
          arch: win64_msvc2017_64
          modules: qtwebengine
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Pull codes
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build MSVC
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          qmake
          nmake
      - name: Package
        env:
          VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC'
        shell: pwsh
        run: |
          New-Item -ItemType Directory DBLParse
          Copy-Item src\release\DBLParse.exe DBLParse
          cd DBLParse
          windeployqt DBLParse.exe
          cd ..
          Compress-Archive -Path DBLParse DBLParse.zip
          echo "Build with GitHub actions." > deploy.log
          echo {{ github.ref }} >> deploy.log
          Get-Date >> deploy.log
      - name: Upload release
        if: startsWith(github.ref, 'refs/heads/master')
        uses: actions/upload-artifact@v1
        with: 
          name: Package
          path: DBLParse.zip
      - name: Upload log
        uses: actions/upload-artifact@v1
        with: 
          name: Package
          path: deploy.log
      